#!/usr/bin/env bash
# author: gotbletu (@youtube|github|odysee)
#         https://www.youtube.com/user/gotbletu
# desc:   launch gui programs with fzf like dmenu/rofi
# depend: fzf sed coreutils findutils dex util-linux

exe() {
  find /usr/share/applications -name "*.desktop" 2>/dev/null
  find /usr/local/share/applications -name "*.desktop" 2>/dev/null
  find "$HOME/.local/share/applications" -name "*.desktop" 2>/dev/null
  find /var/lib/flatpak/exports/share/applications -name "*.desktop" 2>/dev/null
  find "$HOME/.local/share/flatpak/exports/share/applications" -name "*.desktop" 2>/dev/null


  #for i in $(echo $PATH | sed 's/:/\n/g'); do
  #  find $i -maxdepth 1 2>/dev/null
  #done
  find $HOME/.shell -maxdepth 1 2>/dev/null
}


export FZF_DEFAULT_OPTS="-e -i --height=-1 --info=hidden --layout=reverse --scroll-off=5 --tiebreak=index --bind 'home:first,end:last'"


selected=$(exe | sort | fzf -m -d / --with-nth -1 --prompt="select program(s) to open: ")

[ -z "$selected" ] && exit


if [[ ${selected: -8:8} == ".desktop" ]]; then
  setsid dex "$selected" >/dev/null 2>&1 & disown ; 
  sleep 0.2 ; 
else
  $selected
fi
