#!/bin/sh

IFS='
'

# Best used with yt-dlp cause it downloads music in order

[[ ${#@} -lt 1 ]] && echo "you suck nigga" && exit

count=0

echo -n "Enter artist name: "
read -r artist


for i in $(ls -tr)
do
  count=$(( count + 1 ))
  ffmpeg -i $i -metadata track=$count -metadata artist=$artist -c:a copy "${count} ${i}"
  rm $i
done

