#!/bin/sh

IFS='
'

getnosynclyric ()
{
  for lyric in $(find -name "*.lrc")
  do
    hassync=$(sed -n "s/^\[.*/y/p;q" "$lyric")
  
    case "$hassync" in
      y)
  
      ;;
      *) 
        echo "$lyric"
      ;;
    esac
  done
}


while [[ 1 ]]; do
  selectfile=$(getnosynclyric | fuzzel -w 70)

  [[ -z $selectfile ]] && exit

  nvim $selectfile
done

